// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Infrastructure.Context;

#nullable disable

namespace Product.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20250301234052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Product.Infrastructure.Entities.ProductEntity", b =>
                {
                    b.Property<string>("DIN")
                        .HasColumnType("varchar(8)");

                    b.Property<int>("LegalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Shape")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Strength")
                        .HasColumnType("varchar(100)");

                    b.HasKey("DIN");

                    b.ToTable("ProductEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
